name: BedWars
version: 1.0.0-BETA
api: [3.0.0-ALPHA6, 3.0.1]
main: Bluplayz\BedWars
author: NetherTechnology, Bluplayz, & Zeao.
commands:
    Bedwars:
        description: Bedwars Main Command
        aliases: [bw]
    Start:
        description: Bedwars Forcestart Command
